# Lecture 10 Multi-Dimensional Arrays

### Making multi-dimensional arrays

In [152]:
import numpy as np

# input length is now a tuple called the shape
# tuple should have an element for each dimension
# Here's a 2D array that's 3x3
arr_2d = np.zeros((3,3))

print(arr_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [153]:
# We can use a tuple with 3 elements to make a 3D array
arr_3d = np.zeros((3,3,3))

print(arr_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


The numpy arrays have attributes that tell you the basic information about them 

shape - a tuple giving the length of each dimension

size - the total number of elements in the array

ndim - the numer of dimensions the array has

In [154]:
# these attributes for the 2D array
print('shape =', arr_2d.shape)
print('size =', arr_2d.size)
print('ndim =', arr_2d.ndim)

shape = (3, 3)
size = 9
ndim = 2


In [155]:
# these attributes for the 3D array
print('shape =', arr_3d.shape)
print('size =', arr_3d.size)
print('ndim =', arr_3d.ndim)

shape = (3, 3, 3)
size = 27
ndim = 3


In [156]:
# Let's use a function called reshape to make 2D and 3D arrays
# needs to be the same size, but can change the shape
arr_2d = np.reshape(np.arange(9), (3,3))
print('arr_2d')
print(arr_2d)

arr_2d
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [157]:
arr_3d = np.reshape(np.arange(27), (3,3,3))
print('arr_3d')
print(arr_3d)

arr_3d
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### Accessing elements in nD arrays

To get an element of a multi-dimension array, you still use square brackets, but you need to give an index for each dimension

In [158]:
# like so, [first dimension index, second dimesion index]
arr_2d[0,1]

1

In [159]:
# or like this
arr_3d[0,1,2]

5

Let's look at each index

In [160]:
for i in range(arr_2d.shape[0]):
    for j in range(arr_2d.shape[1]):
        print('index [{:d},{:d}] ='.format(i,j), arr_2d[i,j])

index [0,0] = 0
index [0,1] = 1
index [0,2] = 2
index [1,0] = 3
index [1,1] = 4
index [1,2] = 5
index [2,0] = 6
index [2,1] = 7
index [2,2] = 8


In [161]:
for i in range(arr_3d.shape[0]):
    for j in range(arr_3d.shape[1]):
        for k in range(arr_3d.shape[2]):
            print('index [{:d},{:d},{:d}] ='.format(i,j,k), arr_3d[i,j,k])

index [0,0,0] = 0
index [0,0,1] = 1
index [0,0,2] = 2
index [0,1,0] = 3
index [0,1,1] = 4
index [0,1,2] = 5
index [0,2,0] = 6
index [0,2,1] = 7
index [0,2,2] = 8
index [1,0,0] = 9
index [1,0,1] = 10
index [1,0,2] = 11
index [1,1,0] = 12
index [1,1,1] = 13
index [1,1,2] = 14
index [1,2,0] = 15
index [1,2,1] = 16
index [1,2,2] = 17
index [2,0,0] = 18
index [2,0,1] = 19
index [2,0,2] = 20
index [2,1,0] = 21
index [2,1,1] = 22
index [2,1,2] = 23
index [2,2,0] = 24
index [2,2,1] = 25
index [2,2,2] = 26


You can use slicing to get more than one element at a time

In [162]:
# Get the indexes [0,0], [0,1], [1,0], and [1,1]
arr_2d[:2,:2]

array([[0, 1],
       [3, 4]])

In [163]:
# You can get the entirity on one dimension 
# Get everything in the first element of the first dimension 
arr_2d[0]

array([0, 1, 2])

In [164]:
# or the same with the second dimension
# Need : in the first spot to signify all elements
arr_2d[:,0]

array([0, 3, 6])

In [165]:
# this
print(arr_2d[0])
# is the same as this
print(arr_2d[0,:])

[0 1 2]
[0 1 2]


### Basic operations on nD arrays

You can find the min, max, sum, etc on multi-dimension arrays the same as 1D arrays

In [166]:
print('min value of arr_3d =', np.min(arr_3d))
print('max value of arr_3d =', np.max(arr_3d))
print('the sum of all elements in arr_3d =', np.sum(arr_3d))

min value of arr_3d = 0
max value of arr_3d = 26
the sum of all elements in arr_3d = 351


You can also do these operations over certain axes

In [167]:
print(arr_2d)
print(np.max(arr_2d, axis=0))
print(np.max(arr_2d, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[6 7 8]
[2 5 8]


#### Exercise 

- Create a 2D array of random numbers with shape (3,100)
- Do this be creating a 1D array of 300 random values (done in the first cell for you), then reshape it 
- Find the average value of each of the length 100 axes using np.mean() (answer should be an array with length 3)

In [168]:
# Excecute this cell once

# random numbers sampled from a Normal distribution centered around 2
rand_arr_1D = np.random.normal(size=300, loc=2)


In [169]:
# do work here 
rand_arr_2D = np.reshape(rand_arr_1D,(3,100))
#print(rand_arr_2D)


In [170]:
# and here
rand_arr_means = np.mean(rand_arr_2D, axis=1)


In [171]:
print(rand_arr_means)

[2.07976312 1.93737677 1.93472223]


arr_2d is a matrix, let's represent it as 

$A_{ij}$ , a rank 2 matrix

Sums over a certain axis can then be represented as

np.sum($A_{ij}$, axis=0) = $\sum_i A_{ij} = A_{0j} + A_{1j} + ...$

In [172]:
print(arr_2d)
print(np.sum(arr_2d, axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


In [173]:
for i in range(arr_2d.shape[0]):
    print(arr_2d[i])
    if i < arr_2d.shape[0] -1:
        print(' + ')
    else:
        print(' = ')
print(np.sum(arr_2d, axis=0))

[0 1 2]
 + 
[3 4 5]
 + 
[6 7 8]
 = 
[ 9 12 15]


np.sum($A_{ij}$, axis=1) = $\sum_j A_{ij} = A_{j0} + A_{j1} + ...$

In [174]:
print(arr_2d)
print(np.sum(arr_2d, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]


In [175]:
for j in range(arr_2d.shape[1]):
    print(arr_2d[:,j]) 
    if j < arr_2d.shape[1] -1:
        print(' + ')
    else:
        print(' = ')
print(np.sum(arr_2d, axis=1))

[0 3 6]
 + 
[1 4 7]
 + 
[2 5 8]
 = 
[ 3 12 21]


Notice this reduces the number of dimensions (or rank) by 1. 

We can do the same on a rank 3 matrix

np.sum($A_{ijk}$, axis=0) = $\sum_i A_{ijk} = A_{0jk} + A_{1jk} + ...$

In [176]:
# reduces ndim by 1
print(arr_3d)

print(np.sum(arr_3d, axis=0))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]


In [177]:
for i in range(arr_3d.shape[0]):
    print(arr_3d[i])
    if i < arr_3d.shape[0] -1:
        print(' + ')
    else:
        print(' = ')
print(np.sum(arr_3d, axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 + 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
 + 
[[18 19 20]
 [21 22 23]
 [24 25 26]]
 = 
[[27 30 33]
 [36 39 42]
 [45 48 51]]


It's also possible to do over multiple axes at a time

np.sum($A_{ijk}$, axis=(0,1)) = $\sum_j \sum_i A_{ijk} = \sum_j (A_{0jk} + A_{1jk} + ...) = (A_{00k} + A_{10k} + ...) + (A_{01k} + A_{11k} + ...) + ... $

In [178]:
# reduces ndim by 2
print(np.sum(arr_3d, axis=(0,1)))

[108 117 126]


### Array on Array operations (Broadcasting)

Just like 1D arrays, you can do operations on nD-arrays with a scalar without any loops

In [179]:
2*arr_2d

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

and do operations between nD-arrays of the same shape

In [180]:
arr_2d + arr_2d

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

With nD-arrays it's also possible to do operations between arrays with different numbers of dimensions, but they need to be "broadcastable" 

In [181]:
arr_1d = np.arange(3)

# A length 3 1D array plus a (3,3) 2D array
arr_1d + arr_2d

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

Broadcasting numpy arrays is the automatic resizing of an array to allow an operation to happen

when you do arr_1d + arr_2d, behind the scene it automatically inflates arr_1d from a length 3 1D array to a 3x3 2D array. 

You end up with the same as this

In [182]:
arr_1d_to_2d = np.zeros_like(arr_2d)

for i in range(arr_2d.shape[0]):
    arr_1d_to_2d[i] = arr_1d
print(arr_1d_to_2d)

# Let's add these now and we get the same as arr_1d + arr_2d
print(arr_1d_to_2d + arr_2d)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


To be able to broadcast, the arrays need to be easily resizable to allowed operations like this

Let's try some non-square matrices 

In [183]:
# Let's make an array with the shape (4, 2)
arr_42 = np.reshape(np.arange(8), (4,2))
arr_42

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [184]:
# And another with the shape (2, 4)
arr_24 = np.reshape(np.arange(8), (2,4))
arr_24

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [185]:
arr_len4 = np.arange(4)

arr_len4 + arr_42

ValueError: operands could not be broadcast together with shapes (4,) (4,2) 

In [ ]:
arr_len2 = np.arange(2)

arr_len2 + arr_42

array([[0, 2],
       [2, 4],
       [4, 6],
       [6, 8]])

It inflates along the 0th axis

In [ ]:
arr_len2_to_2d = np.zeros_like(arr_42)
for i in range(arr_42.shape[0]):
    arr_len2_to_2d[i] = arr_len2
print(arr_len2_to_2d)

[[0 1]
 [0 1]
 [0 1]
 [0 1]]


If you wanted to do arr_len4 + arr_42 you would either need to do a loop or reshape the array

A convient way to "swap axes" for a 2D array is by taking the transpose, array.T

In [ ]:
arr_42_T = arr_42.T
print(arr_42_T)
arr_42_T

[[0 2 4 6]
 [1 3 5 7]]


array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
# Now it works
arr_len4 + arr_42_T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10]])

In [ ]:
# You can also convert arr_len4 to a 2D array
arr_len4_2d = arr_len4[:,np.newaxis]
print(arr_len4_2d.shape)
print(arr_len4_2d)
arr_len4[:,np.newaxis] + arr_42

(4, 1)
[[0]
 [1]
 [2]
 [3]]


array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])